### ISSUE TITLE
failed calling webhook "admission-webhook.openebs.io": Post https://admission-server-svc.openebs.svc:443/validate?timeout=5s: context deadline exceeded

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/openebs#3046]
## Description
From 1.10.0 Openebs release onwards webhook failure policy has been updated to `Fail` which means any error calling webhook will block the user to perform PVC create/delete operations as accepted.

This error could be due happen below cases:

1. Webhook listen a service with port `:443` , check weather port is open and allowed in security groups settings.
2. Restart of the Node/Rolling update where the admission webhook was running 
3. In HA clusters, admission webhooks affected by dead tcp connections mentioned in https://github.com/kubernetes/kubernetes/issues/80313
4. Client should expose a mechanism to close underlying TCP connections mentioned in https://github.com/kubernetes/client-go/issues/374

## Possible fix:
There is golang/net#55 is an attempt to fix the dead connection problem in the http2 library ( merged yesterday) to fix the above client-go issue.

## Expected Behavior
Admission webhook should recover from dead tcp connections context deadline exceeded error by invalidate the cache associated with the webhook once the first timeout occurred.

## Current Behavior
Failed with error 
```sh
failed calling webhook "admission-webhook.openebs.io": Post https://admission-server-svc.openebs.svc:443/validate?timeout=5s: context deadline exceeded
```
## Possible Solution
Possible workaround and to unblock instantly, is to change the `validatingwebhookConfiguration` failurePolicy to `Ignore` by editing it, using the below command:
```sh
kubectl edit validatingwebhookconfigurations  openebs-validation-webhook-cfg` 
```

## Steps to Reproduce
- Reboot the node where the admission server pod has been schdeuled 

Gethering more info about the cluster and environment this happening (mostly EKS based clusters) 
Last reported issue in konvoy based k8s 1.16.9 cluster.

**Comment by prateekpandey14** [comment]
Findings:
Similar error has been found in RKE based cluster while helping a user in openebs slack,  Node where admission server pod were scheduled has been restarted due to some node configuration changes( increase node resources), and then user started getting this error, and later we tried to rescheduled the admission server pod in different node which resolved the issue.

**Comment by gprasath** [comment]
This issue is observed in konvoy distribution also more consistently.

**Comment by prateekpandey14** [comment]
kube-apiserver logs  pointing out the error `Error proxying data from client to backend: tls: use of closed connection`
```
0611 09:55:49.800488       1 dispatcher.go:110] Failed calling webhook, failing closed admission-webhook.cstor.openebs.io: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I0611 09:55:49.800537       1 trace.go:81] Trace[1480919547]: "GuaranteedUpdate etcd3: *unstructured.Unstructured" (started: 2020-06-11 09:52:39.60519226 +0000 UTC m=+26842.020670941) (total time: 3m10.195334347s):
Trace[1480919547]: [3m10.195334347s] [3m10.195201963s] END
W0611 09:55:49.800557       1 dispatcher.go:110] Failed calling webhook, failing closed admission-webhook.cstor.openebs.io: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I0611 09:55:49.800598       1 trace.go:81] Trace[705383596]: "GuaranteedUpdate etcd3: *unstructured.Unstructured" (started: 2020-06-11 09:52:52.010338062 +0000 UTC m=+26854.425816789) (total time: 2m57.79024965s):
Trace[705383596]: [2m57.79024965s] [2m57.78999389s] END
W0611 09:55:49.800626       1 dispatcher.go:110] Failed calling webhook, failing closed admission-webhook.cstor.openebs.io: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I0611 09:55:49.800677       1 trace.go:81] Trace[204141802]: "GuaranteedUpdate etcd3: *unstructured.Unstructured" (started: 2020-06-11 09:53:22.022329439 +0000 UTC m=+26884.437808176) (total time: 2m27.778337051s):
Trace[204141802]: [2m27.778337051s] [2m27.77807049s] END
W0611 09:55:49.800698       1 dispatcher.go:110] Failed calling webhook, failing closed admission-webhook.cstor.openebs.io: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

W0611 09:55:49.800853       1 dispatcher.go:110] Failed calling webhook, failing closed admission-webhook.cstor.openebs.io: failed calling webhook "admission-webhook.cstor.openebs.io": Post https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s: context deadline exceeded
E0611 09:56:01.073997       1 upgradeaware.go:343] Error proxying data from client to backend: tls: use of closed connection



```

**Comment by valdemarpavesi** [comment]
thanks
k8s v1.19.1
openebs 2.1.0
helm openebs 2.1.0

# kubectl edit validatingwebhookconfigurations  openebs-validation-webhook-cfg
failurePolicy: Ignore

**Comment by prateekpandey14** [comment]
Keeping it open since the issue still exists in k8s, till then its a workaround to help others.

**Comment by invidian** [comment]
@prateekpandey14 I suppose this issue should be re-opened?

**Comment by invidian** [comment]
Not stale

**Comment by maxisam** [comment]
It is weird that it only happens in one of my cluster

**Comment by NinekoTheCat** [comment]
> It is weird that it only happens in one of my cluster.
> 
> Both of them created by Rancher
Not quite, it happened to me too.

**Comment by moshey1** [comment]
I just encountered this issue with EKS v1.21 cluster
`Error from server (InternalError): error when creating "cspc.yaml": Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": Post "https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s": context deadline exceeded`

changing failurePolicy to Ignore didn't fix the issue.

still haven't found a solution

**Comment by prateekpandey14** [comment]
@moshey1 can you verify once that the `failurePolicy` is set to `Ignore` in validatingwebhookconfiguration .

**Comment by moshey1** [comment]
> @moshey1 can you verify once that the `failurePolicy` is set to `Ignore` in validatingwebhookconfiguration .

Yes, it is set to Ignore.
see `kubectl edit validatingwebhookconfigurations  openebs-validation-webhook-cfg` output

`# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2021-08-03T09:10:56Z"
  generation: 3
  labels:
    app: admission-webhook
    openebs.io/component-name: admission-webhook
    openebs.io/version: 2.11.0
  name: openebs-validation-webhook-cfg
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: openebs-admission-server
    uid: a-b-c-d
  resourceVersion: "247456"
  uid: a-b-c-d
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: xxxxxx
    service:
      name: admission-server-svc
      namespace: openebs
      path: /validate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: admission-webhook.openebs.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - DELETE
    resources:
    - persistentvolumeclaims
    scope: '*'
  - apiGroups:
    - openebs.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cstorpoolclusters
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - UPDATE
    resources:
    - cstorvolumeclaims
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - storagepoolclaims
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - namespaces
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
`

**Comment by prateekpandey14** [comment]
@moshey1  there will be another validating webhookconfiguration named as `openebs-cstor-validation-webhook` specific to cstor validation. To disable it you can run 
```
kubectl edit validatingwebhookconfiguration openebs-cstor-validation-webhook
``` 
and set the `FailurePolicy: Ignore`

**Comment by moshey1** [comment]
> @moshey1 there will be another validating webhookconfiguration named as `openebs-cstor-validation-webhook` specific to cstor validation. To disable it you can run
> 
> ```
> kubectl edit validatingwebhookconfiguration openebs-cstor-validation-webhook
> ```
> 
> and set the `FailurePolicy: Ignore`

cstor pool cluster was created successfully
Kudos!

**Comment by furynick** [comment]
Still present in k8s 1.24.3

[Workaround from prateekpandey](https://github.com/openebs/openebs/issues/3046#issuecomment-892412691)14 fixed the problem

**Comment by willzhang** [comment]
仍然存在于 k8s v1.25.3
```

```

https://github.com/openebs/openebs/issues/3046#issuecomment-892412691的解决方法解决了问题

**Comment by brentgroves** [comment]
[fixed problem](https://github.com/openebs/openebs/issues/3046#issuecomment-892412691)
thanks moshey1

**Comment by vyom-soft** [comment]
> 仍然存在于 k8s v1.25.3
> 
> [#3046 (comment)](https://github.com/openebs/openebs/issues/3046#issuecomment-892412691) fixed the problem

The problem is still seen in k8s version 1.24.6 
status:
  conditions:
    - lastTransitionTime: '2023-03-15T07:53:56Z'
      message: >-
        Internal error occurred: failed calling webhook
        "namespace.sidecar-injector.istio.io": failed to call webhook: Post
        "https://istiod.istio-system.svc:443/inject?timeout=10s": context
        deadline exceeded
      reason: FailedCreate
      status: 'True'
      type: ReplicaFailure
  observedGeneration: 1
  replicas: 0

**Comment by avishnu** [comment]
@niladrih has this issue been resolved as part of any of the recent releases?

**Comment by niladrih** [comment]
@avishnu -- This requires a resolution for issue kubernetes/kubernetes#80313.
