### ISSUE TITLE
Add helm based openebs install to user documentation

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#666]
Update the quick install guide with options to install using helm. 
https://github.com/openebs/openebs/blob/master/documentation/source/getting_started/quick_install.rst

Refer to the steps at : https://github.com/openebs/openebs/tree/master/k8s/charts/openebs

**Comment by geekyd** [comment]
@kmova I think this issue is resolved. Is there something left?

**Comment by kmova** [comment]
The steps for installation are as follows on GKE.. 

```
gcloud container clusters list 
gcloud container clusters get-credentials demo-openebs03 --zone us-central1-a 

kubectl get nodes 

curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh 
chmod 700 get_helm.sh 
./get_helm.sh


helm init 
helm version 

kubectl -n kube-system create sa tiller 
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller 
kubectl -n kube-system patch deploy/tiller-deploy -p '{"spec": {"template": {"spec": {"serviceAccountName": "tiller"}}}}' 


git clone https://github.com/openebs/openebs.git
cd openebs/k8s/charts/openebs/
helm install --name openebs . 
kubectl get pods 


cd ../.. 
cd demo/percona/ 
kubectl apply -f demo-percona-mysql-pvc.yaml
```

**Comment by kmova** [comment]
@geekyd -- This issue is not yet resolved. would you like to go for it?

**Comment by vipulgupta2048** [comment]
@kmova  @NisantaSahoo  I am taking this up. Please assign me to this issue.

**Comment by vipulgupta2048** [comment]
Should I edit this instead - https://github.com/openebs/openebs-docs/blob/newstaging/docs/quickstartguide.md

**Comment by prateekpandey14** [comment]
Yes @vipulgupta2048.

**Comment by vipulgupta2048** [comment]
Thanks @prateekpandey14  I am on it.

**Comment by kmova** [comment]
@vipulgupta2048, We are deprecating the openebs charts. https://github.com/openebs/openebs/pull/1532

The instructions should now be modified to include instructions from https://github.com/kubernetes/charts/tree/master/stable/openebs.

Please check if the below doc fixes the issue. 
https://docs.openebs.io/docs/next/installation.html#helm

**Comment by vipulgupta2048** [comment]
@kmova  From what I understand if the charts have been depreciated, by #1532 then the instruction given here are wrong, https://docs.openebs.io/docs/next/installation.html#helm and hence needs to be changed by replacing them with https://github.com/kubernetes/charts/tree/master/stable/openebs. 

Correct me if I am wrong.

**Comment by kmova** [comment]
You are right. Let us update with the instructions provided in https://github.com/kubernetes/charts/tree/master/stable/openebs

**Comment by vipulgupta2048** [comment]
@kmova Please review the https://github.com/openebs/openebs-docs/pull/208

**Comment by vipulgupta2048** [comment]
@kmova Great, I think we should close this as well -  https://github.com/openebs/openebs-docs/pull/208
Since it's finished and not needed anymore. We this issue in the finished section of Documentation clean-up
